services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      # Jenkins home (persistent data)
      - jenkins_home:/var/jenkins_home

      # Docker socket (to run docker inside Jenkins)
      - /var/run/docker.sock:/var/run/docker.sock

    user: root   # REQUIRED to access docker.sock

    command: >
      sh -c "
      apt-get update &&
      apt-get install -y docker.io &&
      exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
